### ISSUE TITLE
app-admin/lsat-0.9.8.2 segfaults on -m gentoo option

### ISSUE THREAD

**Issue by oxr463** [triode3/lsat#1]
This still occurs with the latest release.

See original bug here: https://bugs.gentoo.org/184488

Package bump with patches: https://github.com/gentoo/gentoo/pull/10558

**Reproduction Steps**

Note: latest amd64 stage3 ([1]), used for testing.

```
dev@overlay-devel ~/lsat $ history
    1  git clone https://github.com/triode3/lsat
    2  cd lsat/
    3  ls
    4  ./configure
    5  make
    6  ls
    7  ./lsat -m gentoo
    8  history

dev@overlay-devel ~/lsat $ ./lsat -m gentoo
Segmentation fault (core dumped)

dev@overlay-devel ~/lsat $ cat /etc/os-release
NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo/Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"

dev@overlay-devel ~/lsat $ eselect profile list
... 
  [12]  default/linux/amd64/17.0 (stable) *
...

overlay-devel ~ # cat /var/lib/portage/world
dev-vcs/git
```

[1]: http://distfiles.gentoo.org/releases/amd64/autobuilds/20181204T214502Z/stage3-amd64-20181204T214502Z.tar.xz

**Comment by triode3** [comment]
I can not reproduce on my test server.


rid ~ # lsat -m gentoo
Starting LSAT...
Getting system information...
Running modules...
  Running checkpkgs module...
  Running checkinetd module...
  Running checkhostsfiles module...
  Running checkinittab module...
  Running checklogging module...
faillog: Cannot open /var/log/faillog: No such file or directory
  Running checkset module...
  Running checkwrite module...
  Running checkdotfiles module...
  Running checkpasswd module...
  Running checkfiles module...
  Running checkumask module...
  Running checkftpusers module...
  Running checkrc module...
  Running checkkbd module...
  Running checklimits module...
  Running checkssh module...
  Running checkopenfiles module...
  Running checkissue module...
  Running checkwww module...
  Running checkmd5 module...
  Running checkmodules module...
  Running checksecuretty module...
  Running checkrcperms module...
  Running checknet module...
sh: /sbin/ifconfig: No such file or directory
  Running checknetforward module...
  Running checknetpromisc module...
sh: /sbin/ifconfig: No such file or directory
  Running checkbpass module...
  Running checkipv4 module...
  Running checkx module...
  Running checkftp module...
  Running checklistening module...
  Running checkdisk module...
Finished.
Check lsat.out for details.
Don't forget to check your umask or file perms
when modifying files on the system.

grid ~ # uname -a
Linux grid 4.14.52-gentoo #3 SMP Thu Jul 19 20:41:47 CDT 2018 x86_64 
Intel(R) Core(TM) i5-4570S CPU @ 2.90GHz GenuineIntel GNU/Linux


I see also that the status of the bug is RESOLVED FIXED.

Can you explain why you are saying it is not RESOLVED FIXED? I sent a 
patch 10 years ago.

Thanks.

**Comment by oxr463** [comment]
> I see also that the status of the bug is RESOLVED FIXED.
>
> Can you explain why you are saying it is not RESOLVED FIXED? I sent a
patch 10 years ago.

Yes, it was patched, but during my latest revbump ([1]), we found that it still segfaults.

I was hoping to see if we can fix this upstream, hence this bug report.

[1]: https://github.com/gentoo/gentoo/pull/10558#discussion_r238569649

**Comment by triode3** [comment]
Ah,

Can you send me a total trace? I literally emerged it on two different 
systems, and
it complies and runs on both, with the -m flag.

I will throw up a new vm and launch gentoo and see if I can reproduce it 
yet another
box.

Thank you.

**Comment by oxr463** [comment]
Just to further clarify,

> I literally emerged it on two different systems, and it complies and runs on both, with the -m flag.

The ebuild merges and runs fine _with_ the patch; I'm looking to integrate the patch upstream so that it is no longer neccessary.

**Comment by triode3** [comment]
I think now I am more confused. You are saying when I emerge, it is 
bringing in
an patch that is in the portage tree, or are you saying you are hand 
patching
it with some patch file?

Conversely, do you need my help with the gentoo end of things (e.g. to 
get this
patch in you need me to update something upstream on github or on my 
personal
page (dimlight.org/lsat))?

Thanks.

**Comment by oxr463** [comment]
> You are saying when I emerge, it is bringing in an patch that is in the portage tree...

Exactly, yes.

See: [`app-admin/lsat/files/lsat-0.9.8.2-segfault-fix.patch`](https://github.com/gentoo/gentoo/blob/76bd9342de65f4effdf4bd916eabd938189a6e13/app-admin/lsat/files/lsat-0.9.8.2-segfault-fix.patch)

> Conversely, do you need my help with the gentoo end of things...

Nope, I already did that.

See: https://github.com/gentoo/gentoo/pull/10558

> ...you need me to update something upstream on github...

Yes, I would like to try to see if we can apply this patch here, so that the next ebuild revision no longer requires a patch.

**Comment by triode3** [comment]
I just realized something... on my build machine I am at 0.9.8.4 now.
I will update the github, and it will be at 0.9.8.5

I also uploaded the fixed files to github. They should be ready there.

I will pack them up and put them on the website (dimlight.org/lsat)
when I get back to a PC.

Thanks.

**Comment by triode3** [comment]
Just wondering if you saw my update on github. I should have more time 
in the week ahead to
work on this. I will update the other lsat pages (probably not 
sourceforge however), and
I will also look at the LSAT todo list and update the functionality.

Thanks.

**Comment by oxr463** [comment]
I was expecting a tagged release but for now I can add a development ebuild to test the changes.

**Comment by triode3** [comment]
If you mean a point release on the homepage (I define the homepage as
https://wwww.dimlight.org/lsat) then it has been updated.

Thanks

**Comment by oxr463** [comment]
By releases I meant like this, <https://github.com/triode3/lsat/releases>.

Also, at the bottom of that page it still says `0.9.8.2`:

> Current Version is 0.9.8.2:

But it does look like the release tarballs say `0.9.8.5`.
